import { ReportSubmission } from '@/types';

export const mySubmissions: ReportSubmission[] = [
    {
        id: 'rs-001',
        report_id: 'r-001',
        status: 'submitted',
        media: [
            {
                id: 'm-001',
                name: 'Incident Report.pdf',
                file_name: 'incident-report.pdf',
                mime_type: 'application/pdf',
                size: 245678,
                original_url: '/storage/reports/incident-report.pdf',
            },
        ],
        field_officer: {
            id: 'u-001',
            name: 'Juan Dela Cruz',
            email: 'juan@example.com',
            avatar: null,
        },
        created_at: '2026-01-01T08:15:00Z',
        updated_at: '2026-01-01T08:15:00Z',
    },
    {
        id: 'rs-002',
        report_id: 'r-001',
        status: 'submitted',
        media: [],
        field_officer: {
            id: 'u-002',
            name: 'Maria Santos',
            email: 'maria@example.com',
            avatar: null,
        },
        created_at: '2026-01-02T10:30:00Z',
        updated_at: '2026-01-02T10:30:00Z',
    },
    {
        id: 'rs-003',
        report_id: 'r-002',
        status: 'draft',
        media: [
            {
                id: 'm-003',
                name: 'Photo Evidence.jpg',
                file_name: 'photo-evidence.jpg',
                mime_type: 'image/jpeg',
                size: 523411,
                original_url: '/storage/reports/photo-evidence.jpg',
            },
        ],
        field_officer: {
            id: 'u-003',
            name: 'Pedro Ramos',
            email: 'pedro@example.com',
            avatar: null,
        },
        created_at: '2026-01-03T14:45:00Z',
        updated_at: '2026-01-03T14:45:00Z',
    },
    {
        id: 'rs-004',
        report_id: 'r-002',
        status: 'submitted',
        media: [],
        field_officer: {
            id: 'u-004',
            name: 'Ana Lopez',
            email: 'ana@example.com',
            avatar: null,
        },
        created_at: '2026-01-04T09:00:00Z',
        updated_at: '2026-01-04T09:00:00Z',
    },
    {
        id: 'rs-005',
        report_id: 'r-003',
        status: 'draft',
        media: [],
        field_officer: {
            id: 'u-005',
            name: 'Carlos Mendoza',
            email: 'carlos@example.com',
            avatar: null,
        },
        created_at: '2026-01-05T16:20:00Z',
        updated_at: '2026-01-05T16:20:00Z',
    },
    {
        id: 'rs-006',
        report_id: 'r-003',
        status: 'submitted',
        media: [
            {
                id: 'm-006',
                name: 'Summary.docx',
                file_name: 'summary.docx',
                mime_type:
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                size: 184223,
                original_url: '/storage/reports/summary.docx',
            },
        ],
        field_officer: {
            id: 'u-006',
            name: 'Liza Fernandez',
            email: 'liza@example.com',
            avatar: null,
        },
        created_at: '2026-01-06T11:10:00Z',
        updated_at: '2026-01-06T11:10:00Z',
    },
    {
        id: 'rs-007',
        report_id: 'r-004',
        status: 'submitted',
        media: [],
        field_officer: {
            id: 'u-007',
            name: 'Mark Villanueva',
            email: 'mark@example.com',
            avatar: null,
        },
        created_at: '2026-01-07T13:55:00Z',
        updated_at: '2026-01-07T13:55:00Z',
    },
    {
        id: 'rs-008',
        report_id: 'r-004',
        status: 'draft',
        media: [],
        field_officer: {
            id: 'u-008',
            name: 'Jenny Cruz',
            email: 'jenny@example.com',
            avatar: null,
        },
        created_at: '2026-01-08T07:40:00Z',
        updated_at: '2026-01-08T07:40:00Z',
    },
    {
        id: 'rs-009',
        report_id: 'r-005',
        status: 'submitted',
        media: [],
        field_officer: {
            id: 'u-009',
            name: 'Paolo Reyes',
            email: 'paolo@example.com',
            avatar: null,
        },
        created_at: '2026-01-09T18:05:00Z',
        updated_at: '2026-01-09T18:05:00Z',
    },
    {
        id: 'rs-010',
        report_id: 'r-005',
        status: 'submitted',
        media: [],
        field_officer: {
            id: 'u-010',
            name: 'Grace Lim',
            email: 'grace@example.com',
            avatar: null,
        },
        created_at: '2026-01-10T12:00:00Z',
        updated_at: '2026-01-10T12:00:00Z',
    },
];
